#!/bin/bash
rm -f out/product/phoenix/system/.git/HEAD
rm -f out/product/phoenix/system/.git/index
rm -f out/product/phoenix/system/.git/description
rm -f out/product/phoenix/system/.git/packed-refs
rm -f out/product/phoenix/system/.git/config
rm -rf out/product/phoenix/system/.git
rm -f out/product/phoenix/system/bin/cttyhack
rm -f out/product/phoenix/system/bin/ping6
rm -f out/product/phoenix/system/bin/rev
rm -f out/product/phoenix/system/bin/iostat
rm -f out/product/phoenix/system/bin/ionice
rm -f out/product/phoenix/system/bin/makemime
rm -f out/product/phoenix/system/bin/kbd_mode
rm -f out/product/phoenix/system/bin/fsync
rm -f out/product/phoenix/system/bin/conspy
rm -f out/product/phoenix/system/bin/reformime
rm -f out/product/phoenix/system/bin/ed
rm -f out/product/phoenix/system/bin/stat
rm -f out/product/phoenix/system/bin/fatattr
rm -f out/product/phoenix/system/bin/hush
rm -f out/product/phoenix/system/bin/scriptreplay
rm -f out/product/phoenix/system/bin/mpstat
rm -f out/product/phoenix/system/bin/base64
rm -f out/product/phoenix/system/bin/ipcalc
rm -f out/product/phoenix/system/sbin/fdisk
rm -f out/product/phoenix/system/sbin/ifenslave
rm -f out/product/phoenix/system/sbin/tunctl
rm -f out/product/phoenix/system/sbin/adjtimex
rm -f out/product/phoenix/system/sbin/iwpriv
rm -f out/product/phoenix/system/sbin/blockdev
rm -f out/product/phoenix/system/sbin/modinfo
rm -f out/product/phoenix/system/sbin/mkfs.vfat
rm -f out/product/phoenix/system/sbin/mkfs.fat
rm -f out/product/phoenix/system/sbin/mkfs.minix
rm -f out/product/phoenix/system/sbin/uevent
rm -f out/product/phoenix/system/sbin/mkfs.msdos
rm -f out/product/phoenix/system/sbin/findfs
rm -f out/product/phoenix/system/sbin/mkdosfs
rm -f out/product/phoenix/system/sbin/arp
rm -f out/product/phoenix/system/sbin/fbsplash
rm -f out/product/phoenix/system/sbin/fsck.minix
rm -f out/product/phoenix/system/sbin/zcip
rm -f out/product/phoenix/system/sbin/iwlist
rm -f out/product/phoenix/system/sbin/mke2fs
rm -f out/product/phoenix/system/sbin/acpid
rm -f out/product/phoenix/system/sbin/iwgetid
rm -f out/product/phoenix/system/sbin/slattach
rm -f out/product/phoenix/system/sbin/logread
rm -f out/product/phoenix/system/sbin/iwconfig
rm -f out/product/phoenix/system/sbin/depmod
rm -f out/product/phoenix/system/sbin/iwspy
rm -f out/product/phoenix/system/sbin/mkfs.ext2
rm -f out/product/phoenix/system/sbin/ipneigh
rm -f out/product/phoenix/system/sbin/bootchartd
rm -f out/product/phoenix/system/sbin/raidautorun
rm -f out/product/phoenix/system/lib/libthread_db-1.0.so
rm -f out/product/phoenix/system/lib/libthread_db.so.1
rm -rf out/product/phoenix/system/var/lib/sudo
rm -rf out/product/phoenix/system/var/lib/sudo/lectured
rm -f out/product/phoenix/system/etc/mke2fs.conf
rm -f out/product/phoenix/system/etc/sudoers
rm -f out/product/phoenix/system/etc/init.d/S50telnet
rm -rf out/product/phoenix/system/etc/sudoers.d
rm -f out/product/phoenix/system/usr/bin/nsenter
rm -f out/product/phoenix/system/usr/bin/ntfs-3g.usermap
rm -f out/product/phoenix/system/usr/bin/lpr
rm -f out/product/phoenix/system/usr/bin/rx
rm -f out/product/phoenix/system/usr/bin/nc
rm -f out/product/phoenix/system/usr/bin/pstree
rm -f out/product/phoenix/system/usr/bin/timeout
rm -f out/product/phoenix/system/usr/bin/setuidgid
rm -f out/product/phoenix/system/usr/bin/split
rm -f out/product/phoenix/system/usr/bin/flock
rm -f out/product/phoenix/system/usr/bin/envuidgid
rm -f out/product/phoenix/system/usr/bin/volname
rm -f out/product/phoenix/system/usr/bin/lpq
rm -f out/product/phoenix/system/usr/bin/cryptpw
rm -f out/product/phoenix/system/usr/bin/ntfs-3g.probe
rm -f out/product/phoenix/system/usr/bin/unshare
rm -f out/product/phoenix/system/usr/bin/showkey
rm -f out/product/phoenix/system/usr/bin/sudoreplay
rm -f out/product/phoenix/system/usr/bin/strace-log-merge
rm -f out/product/phoenix/system/usr/bin/traceroute6
rm -f out/product/phoenix/system/usr/bin/gdbserver
rm -f out/product/phoenix/system/usr/bin/whois
rm -f out/product/phoenix/system/usr/bin/unlink
rm -f out/product/phoenix/system/usr/bin/softlimit
rm -f out/product/phoenix/system/usr/bin/tcpsvd
rm -f out/product/phoenix/system/usr/bin/ftpget
rm -f out/product/phoenix/system/usr/bin/blkdiscard
rm -f out/product/phoenix/system/usr/bin/udpsvd
rm -f out/product/phoenix/system/usr/bin/pwdx
rm -f out/product/phoenix/system/usr/bin/man
rm -f out/product/phoenix/system/usr/bin/ntfs-3g
rm -f out/product/phoenix/system/usr/bin/beep
rm -f out/product/phoenix/system/usr/bin/mkpasswd
rm -f out/product/phoenix/system/usr/bin/pgrep
rm -f out/product/phoenix/system/usr/bin/ftpput
rm -f out/product/phoenix/system/usr/bin/runsvdir
rm -f out/product/phoenix/system/usr/bin/smemcap
rm -f out/product/phoenix/system/usr/bin/envdir
rm -f out/product/phoenix/system/usr/bin/sudoedit
rm -f out/product/phoenix/system/usr/bin/lowntfs-3g
rm -f out/product/phoenix/system/usr/bin/chpst
rm -f out/product/phoenix/system/usr/bin/hd
rm -f out/product/phoenix/system/usr/bin/ntfs-3g.secaudit
rm -f out/product/phoenix/system/usr/bin/pmap
rm -f out/product/phoenix/system/usr/bin/fgconsole
rm -f out/product/phoenix/system/usr/bin/script
rm -f out/product/phoenix/system/usr/bin/groups
rm -f out/product/phoenix/system/usr/bin/ttysize
rm -f out/product/phoenix/system/usr/bin/runsv
rm -f out/product/phoenix/system/usr/bin/truncate
rm -f out/product/phoenix/system/usr/bin/pkill
rm -f out/product/phoenix/system/usr/bin/sudo
rm -f out/product/phoenix/system/usr/bin/pscan
rm -f out/product/phoenix/system/usr/bin/tree
rm -f out/product/phoenix/system/usr/bin/strace
rm -f out/product/phoenix/system/usr/bin/cal
rm -f out/product/phoenix/system/usr/bin/nmeter
rm -f out/product/phoenix/system/usr/sbin/fakeidentd
rm -f out/product/phoenix/system/usr/sbin/ftpd
rm -f out/product/phoenix/system/usr/sbin/iptables-restore
rm -f out/product/phoenix/system/usr/sbin/popmaildir
rm -f out/product/phoenix/system/usr/sbin/ubicrc32
rm -f out/product/phoenix/system/usr/sbin/iptables
rm -f out/product/phoenix/system/usr/sbin/i2cset
rm -f out/product/phoenix/system/usr/sbin/setfont
rm -f out/product/phoenix/system/usr/sbin/ip6tables-save
rm -f out/product/phoenix/system/usr/sbin/i2cdetect
rm -f out/product/phoenix/system/usr/sbin/e4crypt
rm -f out/product/phoenix/system/usr/sbin/add-shell
rm -f out/product/phoenix/system/usr/sbin/ubiformat
rm -f out/product/phoenix/system/usr/sbin/i2cget
rm -f out/product/phoenix/system/usr/sbin/svlogd
rm -f out/product/phoenix/system/usr/sbin/rdev
rm -f out/product/phoenix/system/usr/sbin/chat
rm -f out/product/phoenix/system/usr/sbin/ip6tables
rm -f out/product/phoenix/system/usr/sbin/iptables-save
rm -f out/product/phoenix/system/usr/sbin/telnetd
rm -f out/product/phoenix/system/usr/sbin/mkfs.ext4
rm -f out/product/phoenix/system/usr/sbin/nandtest
rm -f out/product/phoenix/system/usr/sbin/tftpd
rm -f out/product/phoenix/system/usr/sbin/lpd
rm -f out/product/phoenix/system/usr/sbin/rtcwake
rm -f out/product/phoenix/system/usr/sbin/nbd-client
rm -f out/product/phoenix/system/usr/sbin/visudo
rm -f out/product/phoenix/system/usr/sbin/fbset
rm -f out/product/phoenix/system/usr/sbin/httpd
rm -f out/product/phoenix/system/usr/sbin/ip6tables-restore
rm -f out/product/phoenix/system/usr/sbin/ifplugd
rm -f out/product/phoenix/system/usr/sbin/mke2fs
rm -f out/product/phoenix/system/usr/sbin/ubinfo
rm -f out/product/phoenix/system/usr/sbin/i2cdump
rm -f out/product/phoenix/system/usr/sbin/ubiblock
rm -f out/product/phoenix/system/usr/sbin/ntpd
rm -f out/product/phoenix/system/usr/sbin/mkfs.ext4dev
rm -f out/product/phoenix/system/usr/sbin/mkfs.ext3
rm -f out/product/phoenix/system/usr/sbin/readahead
rm -f out/product/phoenix/system/usr/sbin/sendmail
rm -f out/product/phoenix/system/usr/sbin/mkfs.ext2
rm -f out/product/phoenix/system/usr/sbin/ubinize
rm -f out/product/phoenix/system/usr/sbin/brctl
rm -f out/product/phoenix/system/usr/sbin/remove-shell
rm -f out/product/phoenix/system/usr/sbin/chpasswd
rm -f out/product/phoenix/system/usr/sbin/xtables-multi
rm -f out/product/phoenix/system/usr/sbin/powertop
rm -f out/product/phoenix/system/usr/lib/libip6tc.so.0.1.0
rm -f out/product/phoenix/system/usr/lib/libss.so.2
rm -f out/product/phoenix/system/usr/lib/libss.so
rm -f out/product/phoenix/system/usr/lib/libext2fs.so.2.4
rm -f out/product/phoenix/system/usr/lib/libiptc.so
rm -f out/product/phoenix/system/usr/lib/libntfs-3g.so.87
rm -f out/product/phoenix/system/usr/lib/libxtables.so.12
rm -f out/product/phoenix/system/usr/lib/libext2fs.so.2
rm -f out/product/phoenix/system/usr/lib/libxtables.so
rm -f out/product/phoenix/system/usr/lib/libntfs-3g.so
rm -f out/product/phoenix/system/usr/lib/libe2p.so.2
rm -f out/product/phoenix/system/usr/lib/libe2p.so
rm -f out/product/phoenix/system/usr/lib/libip6tc.so.0
rm -f out/product/phoenix/system/usr/lib/libip6tc.so
rm -f out/product/phoenix/system/usr/lib/libiptc.so.0
rm -f out/product/phoenix/system/usr/lib/libip4tc.so.0.1.0
rm -f out/product/phoenix/system/usr/lib/libntfs-3g.so.87.0.0
rm -f out/product/phoenix/system/usr/lib/libe2p.so.2.3
rm -f out/product/phoenix/system/usr/lib/libcom_err.so.2
rm -f out/product/phoenix/system/usr/lib/libcom_err.so
rm -f out/product/phoenix/system/usr/lib/libip4tc.so.0
rm -f out/product/phoenix/system/usr/lib/libss.so.2.0
rm -f out/product/phoenix/system/usr/lib/libcom_err.so.2.1
rm -f out/product/phoenix/system/usr/lib/libxtables.so.12.0.0
rm -f out/product/phoenix/system/usr/lib/libiptc.so.0.0.0
rm -f out/product/phoenix/system/usr/lib/libext2fs.so
rm -f out/product/phoenix/system/usr/lib/libip4tc.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_CLUSTERIP.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_owner.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_DNAT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_TPROXY.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_limit.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_NETMAP.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_bpf.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_statistic.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_dscp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_CLASSIFY.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_time.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_u32.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_iprange.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_state.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_NETMAP.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_rateest.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_mh.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_dccp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_DNAT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_LOG.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_hbh.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_TCPOPTSTRIP.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_CHECKSUM.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_devgroup.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_quota.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_TRACE.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_SYNPROXY.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_LED.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_connlimit.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_realm.so
rm -f out/product/phoenix/system/usr/lib/xtables/libebt_mark_m.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_ah.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_CONNMARK.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_hashlimit.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_tcp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_LOG.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_TOS.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_TCPMSS.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_RATEEST.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_osf.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_dst.so
rm -f out/product/phoenix/system/usr/lib/xtables/libebt_ip.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_policy.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_SET.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_pkttype.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_multiport.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_udp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_SNAT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_ttl.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_connmark.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_REJECT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_ecn.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_ah.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_recent.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_mac.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_CONNSECMARK.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_TTL.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_NFLOG.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_TEE.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_physdev.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_nfacct.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_HMARK.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_tcpmss.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_REDIRECT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_addrtype.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_helper.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_DNPT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_NOTRACK.so
rm -f out/product/phoenix/system/usr/lib/xtables/libebt_log.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_REJECT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_length.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_CT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_HL.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_cluster.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_SECMARK.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_ipv6header.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_MASQUERADE.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_cgroup.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_connbytes.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_conntrack.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_MASQUERADE.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_IDLETIMER.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_eui64.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_ECN.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_standard.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_NFQUEUE.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_set.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_frag.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_tos.so
rm -f out/product/phoenix/system/usr/lib/xtables/libebt_802_3.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_cpu.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_icmp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_ULOG.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_hl.so
rm -f out/product/phoenix/system/usr/lib/xtables/libipt_SNAT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_REDIRECT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_comment.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_DSCP.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_mark.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_rpfilter.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_ipcomp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_socket.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_esp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_SNPT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_mangle.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_string.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_sctp.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_icmp6.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_AUDIT.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_ipvs.so
rm -f out/product/phoenix/system/usr/lib/xtables/libxt_MARK.so
rm -f out/product/phoenix/system/usr/lib/xtables/libip6t_rt.so
rm -rf out/product/phoenix/system/usr/lib/xtables
rm -f out/product/phoenix/system/usr/libexec/sudo/libsudo_util.so.0
rm -f out/product/phoenix/system/usr/libexec/sudo/system_group.so
rm -f out/product/phoenix/system/usr/libexec/sudo/libsudo_util.so
rm -f out/product/phoenix/system/usr/libexec/sudo/group_file.so
rm -f out/product/phoenix/system/usr/libexec/sudo/libsudo_util.so.0.0.0
rm -f out/product/phoenix/system/usr/libexec/sudo/sudo_noexec.so
rm -f out/product/phoenix/system/usr/libexec/sudo/sudoers.so
rm -rf out/product/phoenix/system/usr/libexec/sudo
rm -f out/product/phoenix/system/usr/share/glib-2.0/gdb/gobject_gdb.py
rm -f out/product/phoenix/system/usr/share/glib-2.0/gdb/glib_gdb.py
rm -rf out/product/phoenix/system/usr/share/glib-2.0/gdb
rm -rf out/product/phoenix/system/run/sudo
