#!/bin/bash
rm -f out/product/halley2/system/.git/HEAD
rm -f out/product/halley2/system/.git/index
rm -f out/product/halley2/system/.git/description
rm -f out/product/halley2/system/.git/packed-refs
rm -f out/product/halley2/system/.git/config
rm -rf out/product/halley2/system/.git
rm -f out/product/halley2/system/bin/cttyhack
rm -f out/product/halley2/system/bin/ping6
rm -f out/product/halley2/system/bin/rev
rm -f out/product/halley2/system/bin/iostat
rm -f out/product/halley2/system/bin/ionice
rm -f out/product/halley2/system/bin/makemime
rm -f out/product/halley2/system/bin/kbd_mode
rm -f out/product/halley2/system/bin/fsync
rm -f out/product/halley2/system/bin/conspy
rm -f out/product/halley2/system/bin/reformime
rm -f out/product/halley2/system/bin/ed
rm -f out/product/halley2/system/bin/stat
rm -f out/product/halley2/system/bin/fatattr
rm -f out/product/halley2/system/bin/hush
rm -f out/product/halley2/system/bin/scriptreplay
rm -f out/product/halley2/system/bin/mpstat
rm -f out/product/halley2/system/bin/base64
rm -f out/product/halley2/system/bin/ipcalc
rm -f out/product/halley2/system/sbin/fdisk
rm -f out/product/halley2/system/sbin/ifenslave
rm -f out/product/halley2/system/sbin/tunctl
rm -f out/product/halley2/system/sbin/adjtimex
rm -f out/product/halley2/system/sbin/iwpriv
rm -f out/product/halley2/system/sbin/blockdev
rm -f out/product/halley2/system/sbin/modinfo
rm -f out/product/halley2/system/sbin/mkfs.vfat
rm -f out/product/halley2/system/sbin/mkfs.fat
rm -f out/product/halley2/system/sbin/mkfs.minix
rm -f out/product/halley2/system/sbin/uevent
rm -f out/product/halley2/system/sbin/mkfs.msdos
rm -f out/product/halley2/system/sbin/findfs
rm -f out/product/halley2/system/sbin/mkdosfs
rm -f out/product/halley2/system/sbin/arp
rm -f out/product/halley2/system/sbin/fbsplash
rm -f out/product/halley2/system/sbin/fsck.minix
rm -f out/product/halley2/system/sbin/zcip
rm -f out/product/halley2/system/sbin/iwlist
rm -f out/product/halley2/system/sbin/mke2fs
rm -f out/product/halley2/system/sbin/acpid
rm -f out/product/halley2/system/sbin/iwgetid
rm -f out/product/halley2/system/sbin/slattach
rm -f out/product/halley2/system/sbin/logread
rm -f out/product/halley2/system/sbin/iwconfig
rm -f out/product/halley2/system/sbin/depmod
rm -f out/product/halley2/system/sbin/iwspy
rm -f out/product/halley2/system/sbin/mkfs.ext2
rm -f out/product/halley2/system/sbin/ipneigh
rm -f out/product/halley2/system/sbin/bootchartd
rm -f out/product/halley2/system/sbin/raidautorun
rm -f out/product/halley2/system/lib/libthread_db-1.0.so
rm -f out/product/halley2/system/lib/libthread_db.so.1
rm -rf out/product/halley2/system/var/lib/alsa
rm -rf out/product/halley2/system/var/lib/sudo
rm -rf out/product/halley2/system/var/lib/sudo/lectured
rm -f out/product/halley2/system/etc/mke2fs.conf
rm -f out/product/halley2/system/etc/sudoers
rm -f out/product/halley2/system/etc/init.d/S50telnet
rm -rf out/product/halley2/system/etc/sudoers.d
rm -f out/product/halley2/system/usr/bin/nsenter
rm -f out/product/halley2/system/usr/bin/ntfs-3g.usermap
rm -f out/product/halley2/system/usr/bin/lpr
rm -f out/product/halley2/system/usr/bin/rx
rm -f out/product/halley2/system/usr/bin/nc
rm -f out/product/halley2/system/usr/bin/pstree
rm -f out/product/halley2/system/usr/bin/timeout
rm -f out/product/halley2/system/usr/bin/setuidgid
rm -f out/product/halley2/system/usr/bin/split
rm -f out/product/halley2/system/usr/bin/flock
rm -f out/product/halley2/system/usr/bin/envuidgid
rm -f out/product/halley2/system/usr/bin/volname
rm -f out/product/halley2/system/usr/bin/lpq
rm -f out/product/halley2/system/usr/bin/cryptpw
rm -f out/product/halley2/system/usr/bin/ntfs-3g.probe
rm -f out/product/halley2/system/usr/bin/unshare
rm -f out/product/halley2/system/usr/bin/aplay
rm -f out/product/halley2/system/usr/bin/showkey
rm -f out/product/halley2/system/usr/bin/sudoreplay
rm -f out/product/halley2/system/usr/bin/strace-log-merge
rm -f out/product/halley2/system/usr/bin/traceroute6
rm -f out/product/halley2/system/usr/bin/gdbserver
rm -f out/product/halley2/system/usr/bin/whois
rm -f out/product/halley2/system/usr/bin/unlink
rm -f out/product/halley2/system/usr/bin/softlimit
rm -f out/product/halley2/system/usr/bin/tcpsvd
rm -f out/product/halley2/system/usr/bin/ftpget
rm -f out/product/halley2/system/usr/bin/blkdiscard
rm -f out/product/halley2/system/usr/bin/arecord
rm -f out/product/halley2/system/usr/bin/udpsvd
rm -f out/product/halley2/system/usr/bin/pwdx
rm -f out/product/halley2/system/usr/bin/man
rm -f out/product/halley2/system/usr/bin/ntfs-3g
rm -f out/product/halley2/system/usr/bin/beep
rm -f out/product/halley2/system/usr/bin/mkpasswd
rm -f out/product/halley2/system/usr/bin/pgrep
rm -f out/product/halley2/system/usr/bin/ftpput
rm -f out/product/halley2/system/usr/bin/runsvdir
rm -f out/product/halley2/system/usr/bin/smemcap
rm -f out/product/halley2/system/usr/bin/envdir
rm -f out/product/halley2/system/usr/bin/sudoedit
rm -f out/product/halley2/system/usr/bin/lowntfs-3g
rm -f out/product/halley2/system/usr/bin/chpst
rm -f out/product/halley2/system/usr/bin/amixer
rm -f out/product/halley2/system/usr/bin/hd
rm -f out/product/halley2/system/usr/bin/ntfs-3g.secaudit
rm -f out/product/halley2/system/usr/bin/pmap
rm -f out/product/halley2/system/usr/bin/aserver
rm -f out/product/halley2/system/usr/bin/fgconsole
rm -f out/product/halley2/system/usr/bin/script
rm -f out/product/halley2/system/usr/bin/groups
rm -f out/product/halley2/system/usr/bin/ttysize
rm -f out/product/halley2/system/usr/bin/runsv
rm -f out/product/halley2/system/usr/bin/truncate
rm -f out/product/halley2/system/usr/bin/pkill
rm -f out/product/halley2/system/usr/bin/sudo
rm -f out/product/halley2/system/usr/bin/pscan
rm -f out/product/halley2/system/usr/bin/tree
rm -f out/product/halley2/system/usr/bin/strace
rm -f out/product/halley2/system/usr/bin/cal
rm -f out/product/halley2/system/usr/bin/nmeter
rm -f out/product/halley2/system/usr/sbin/fakeidentd
rm -f out/product/halley2/system/usr/sbin/ftpd
rm -f out/product/halley2/system/usr/sbin/iptables-restore
rm -f out/product/halley2/system/usr/sbin/popmaildir
rm -f out/product/halley2/system/usr/sbin/ubicrc32
rm -f out/product/halley2/system/usr/sbin/iptables
rm -f out/product/halley2/system/usr/sbin/i2cset
rm -f out/product/halley2/system/usr/sbin/setfont
rm -f out/product/halley2/system/usr/sbin/ip6tables-save
rm -f out/product/halley2/system/usr/sbin/i2cdetect
rm -f out/product/halley2/system/usr/sbin/e4crypt
rm -f out/product/halley2/system/usr/sbin/add-shell
rm -f out/product/halley2/system/usr/sbin/ubiformat
rm -f out/product/halley2/system/usr/sbin/i2cget
rm -f out/product/halley2/system/usr/sbin/svlogd
rm -f out/product/halley2/system/usr/sbin/rdev
rm -f out/product/halley2/system/usr/sbin/chat
rm -f out/product/halley2/system/usr/sbin/ip6tables
rm -f out/product/halley2/system/usr/sbin/iptables-save
rm -f out/product/halley2/system/usr/sbin/telnetd
rm -f out/product/halley2/system/usr/sbin/mkfs.ext4
rm -f out/product/halley2/system/usr/sbin/nandtest
rm -f out/product/halley2/system/usr/sbin/tftpd
rm -f out/product/halley2/system/usr/sbin/lpd
rm -f out/product/halley2/system/usr/sbin/rtcwake
rm -f out/product/halley2/system/usr/sbin/nbd-client
rm -f out/product/halley2/system/usr/sbin/visudo
rm -f out/product/halley2/system/usr/sbin/fbset
rm -f out/product/halley2/system/usr/sbin/httpd
rm -f out/product/halley2/system/usr/sbin/ip6tables-restore
rm -f out/product/halley2/system/usr/sbin/ifplugd
rm -f out/product/halley2/system/usr/sbin/mke2fs
rm -f out/product/halley2/system/usr/sbin/ubinfo
rm -f out/product/halley2/system/usr/sbin/i2cdump
rm -f out/product/halley2/system/usr/sbin/ubiblock
rm -f out/product/halley2/system/usr/sbin/ntpd
rm -f out/product/halley2/system/usr/sbin/mkfs.ext4dev
rm -f out/product/halley2/system/usr/sbin/mkfs.ext3
rm -f out/product/halley2/system/usr/sbin/readahead
rm -f out/product/halley2/system/usr/sbin/sendmail
rm -f out/product/halley2/system/usr/sbin/mkfs.ext2
rm -f out/product/halley2/system/usr/sbin/ubinize
rm -f out/product/halley2/system/usr/sbin/brctl
rm -f out/product/halley2/system/usr/sbin/remove-shell
rm -f out/product/halley2/system/usr/sbin/chpasswd
rm -f out/product/halley2/system/usr/sbin/xtables-multi
rm -f out/product/halley2/system/usr/sbin/powertop
rm -f out/product/halley2/system/usr/lib/libip6tc.so.0.1.0
rm -f out/product/halley2/system/usr/lib/libss.so.2
rm -f out/product/halley2/system/usr/lib/libss.so
rm -f out/product/halley2/system/usr/lib/libext2fs.so.2.4
rm -f out/product/halley2/system/usr/lib/libiptc.so
rm -f out/product/halley2/system/usr/lib/libntfs-3g.so.87
rm -f out/product/halley2/system/usr/lib/libasound.so.2
rm -f out/product/halley2/system/usr/lib/libxtables.so.12
rm -f out/product/halley2/system/usr/lib/libext2fs.so.2
rm -f out/product/halley2/system/usr/lib/libxtables.so
rm -f out/product/halley2/system/usr/lib/libntfs-3g.so
rm -f out/product/halley2/system/usr/lib/libe2p.so.2
rm -f out/product/halley2/system/usr/lib/libe2p.so
rm -f out/product/halley2/system/usr/lib/libip6tc.so.0
rm -f out/product/halley2/system/usr/lib/libip6tc.so
rm -f out/product/halley2/system/usr/lib/libasound.so
rm -f out/product/halley2/system/usr/lib/libasound.so.2.0.0
rm -f out/product/halley2/system/usr/lib/libiptc.so.0
rm -f out/product/halley2/system/usr/lib/libip4tc.so.0.1.0
rm -f out/product/halley2/system/usr/lib/libntfs-3g.so.87.0.0
rm -f out/product/halley2/system/usr/lib/libe2p.so.2.3
rm -f out/product/halley2/system/usr/lib/libcom_err.so.2
rm -f out/product/halley2/system/usr/lib/libcom_err.so
rm -f out/product/halley2/system/usr/lib/libip4tc.so.0
rm -f out/product/halley2/system/usr/lib/libss.so.2.0
rm -f out/product/halley2/system/usr/lib/libcom_err.so.2.1
rm -f out/product/halley2/system/usr/lib/libxtables.so.12.0.0
rm -f out/product/halley2/system/usr/lib/libiptc.so.0.0.0
rm -f out/product/halley2/system/usr/lib/libext2fs.so
rm -f out/product/halley2/system/usr/lib/libip4tc.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_CLUSTERIP.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_owner.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_DNAT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_TPROXY.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_limit.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_NETMAP.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_bpf.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_statistic.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_dscp.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_CLASSIFY.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_time.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_u32.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_iprange.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_state.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_NETMAP.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_rateest.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_mh.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_dccp.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_DNAT.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_LOG.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_hbh.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_TCPOPTSTRIP.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_CHECKSUM.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_devgroup.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_quota.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_TRACE.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_SYNPROXY.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_LED.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_connlimit.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_realm.so
rm -f out/product/halley2/system/usr/lib/xtables/libebt_mark_m.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_ah.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_CONNMARK.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_hashlimit.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_tcp.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_LOG.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_TOS.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_TCPMSS.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_RATEEST.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_osf.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_dst.so
rm -f out/product/halley2/system/usr/lib/xtables/libebt_ip.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_policy.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_SET.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_pkttype.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_multiport.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_udp.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_SNAT.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_ttl.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_connmark.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_REJECT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_ecn.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_ah.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_recent.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_mac.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_CONNSECMARK.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_TTL.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_NFLOG.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_TEE.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_physdev.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_nfacct.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_HMARK.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_tcpmss.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_REDIRECT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_addrtype.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_helper.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_DNPT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_NOTRACK.so
rm -f out/product/halley2/system/usr/lib/xtables/libebt_log.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_REJECT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_length.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_CT.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_HL.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_cluster.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_SECMARK.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_ipv6header.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_MASQUERADE.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_cgroup.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_connbytes.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_conntrack.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_MASQUERADE.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_IDLETIMER.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_eui64.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_ECN.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_standard.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_NFQUEUE.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_set.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_frag.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_tos.so
rm -f out/product/halley2/system/usr/lib/xtables/libebt_802_3.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_cpu.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_icmp.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_ULOG.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_hl.so
rm -f out/product/halley2/system/usr/lib/xtables/libipt_SNAT.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_REDIRECT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_comment.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_DSCP.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_mark.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_rpfilter.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_ipcomp.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_socket.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_esp.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_SNPT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_mangle.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_string.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_sctp.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_icmp6.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_AUDIT.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_ipvs.so
rm -f out/product/halley2/system/usr/lib/xtables/libxt_MARK.so
rm -f out/product/halley2/system/usr/lib/xtables/libip6t_rt.so
rm -rf out/product/halley2/system/usr/lib/xtables
rm -f out/product/halley2/system/usr/libexec/sudo/libsudo_util.so.0
rm -f out/product/halley2/system/usr/libexec/sudo/system_group.so
rm -f out/product/halley2/system/usr/libexec/sudo/libsudo_util.so
rm -f out/product/halley2/system/usr/libexec/sudo/group_file.so
rm -f out/product/halley2/system/usr/libexec/sudo/libsudo_util.so.0.0.0
rm -f out/product/halley2/system/usr/libexec/sudo/sudo_noexec.so
rm -f out/product/halley2/system/usr/libexec/sudo/sudoers.so
rm -rf out/product/halley2/system/usr/libexec/sudo
rm -f out/product/halley2/system/usr/share/alsa/alsa.conf
rm -f out/product/halley2/system/usr/share/alsa/sndo-mixer.alisp
rm -rf out/product/halley2/system/usr/share/alsa
rm -f out/product/halley2/system/usr/share/alsa/pcm/default.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/side.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/surround71.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/dsnoop.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/front.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/iec958.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/surround51.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/rear.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/surround50.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/center_lfe.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/modem.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/dmix.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/surround41.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/surround21.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/surround40.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/hdmi.conf
rm -f out/product/halley2/system/usr/share/alsa/pcm/dpl.conf
rm -rf out/product/halley2/system/usr/share/alsa/pcm
rm -f out/product/halley2/system/usr/share/alsa/alsa.conf.d/README
rm -rf out/product/halley2/system/usr/share/alsa/alsa.conf.d
rm -f out/product/halley2/system/usr/share/alsa/cards/FWSpeakers.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Audigy.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/PMacToonie.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ES1968.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CMI8738-MC6.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ATIIXP-SPDMA.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ATIIXP-MODEM.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Maestro3.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Audigy2.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CMI8788.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/GUS.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/SB-XFi.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/PMac.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/NFORCE.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/aliases.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VIA8233.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/aliases.alisp
rm -f out/product/halley2/system/usr/share/alsa/cards/ICH4.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/PS3.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VX222.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VIA8233A.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ENS1370.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VXPocket.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/PC-Speaker.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VXPocket440.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CS46xx.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/EMU10K1.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/FireWave.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ATIIXP.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/TRID4DWAVENX.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/AACI.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/USB-Audio.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/RME9636.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/YMF744.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/SI7018.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/AU8820.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/AU8830.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/RME9652.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Aureon71.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CMI8338.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/EMU10K1X.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/AU8810.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/HDA-Intel.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/FM801.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CMI8338-SWIEC.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Echo_Echo3G.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Aureon51.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ENS1371.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VIA8237.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CMI8738-MC8.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/Loopback.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ICE1724.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ICH.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ICH-MODEM.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/CA0106.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/VIA686A.conf
rm -f out/product/halley2/system/usr/share/alsa/cards/ICE1712.conf
rm -rf out/product/halley2/system/usr/share/alsa/cards
rm -f out/product/halley2/system/usr/share/alsa/cards/SI7018/sndoc-mixer.alisp
rm -f out/product/halley2/system/usr/share/alsa/cards/SI7018/sndop-mixer.alisp
rm -rf out/product/halley2/system/usr/share/alsa/cards/SI7018
rm -rf out/product/halley2/system/usr/share/alsa/topology
rm -f out/product/halley2/system/usr/share/alsa/topology/bxtrt298/bxt_i2s.conf
rm -rf out/product/halley2/system/usr/share/alsa/topology/bxtrt298
rm -f out/product/halley2/system/usr/share/alsa/topology/broadwell/broadwell.conf
rm -rf out/product/halley2/system/usr/share/alsa/topology/broadwell
rm -f out/product/halley2/system/usr/share/alsa/topology/sklrt286/skl_i2s.conf
rm -rf out/product/halley2/system/usr/share/alsa/topology/sklrt286
rm -rf out/product/halley2/system/usr/share/alsa/ucm
rm -f out/product/halley2/system/usr/share/alsa/ucm/PAZ00/PAZ00.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/PAZ00/Record.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/PAZ00/HiFi.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/PAZ00
rm -f out/product/halley2/system/usr/share/alsa/ucm/chtrt5645/chtrt5645.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/chtrt5645/HiFi.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/chtrt5645
rm -f out/product/halley2/system/usr/share/alsa/ucm/DAISY-I2S/DAISY-I2S.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/DAISY-I2S/HiFi.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/DAISY-I2S
rm -f out/product/halley2/system/usr/share/alsa/ucm/VEYRON-I2S/HiFi.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/VEYRON-I2S/VEYRON-I2S.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/VEYRON-I2S
rm -f out/product/halley2/system/usr/share/alsa/ucm/broadwell-rt286/HiFi
rm -f out/product/halley2/system/usr/share/alsa/ucm/broadwell-rt286/broadwell-rt286.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/broadwell-rt286
rm -f out/product/halley2/system/usr/share/alsa/ucm/DB410c/HiFi
rm -f out/product/halley2/system/usr/share/alsa/ucm/DB410c/DB410c.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/DB410c/HDMI
rm -rf out/product/halley2/system/usr/share/alsa/ucm/DB410c
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/FMAnalog
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/voice
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/record
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/PandaBoardES.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/voiceCall
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/hifiLP
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES/hifi
rm -rf out/product/halley2/system/usr/share/alsa/ucm/PandaBoardES
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/FMAnalog
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/voice
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/record
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/SDP4430.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/voiceCall
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/hifiLP
rm -f out/product/halley2/system/usr/share/alsa/ucm/SDP4430/hifi
rm -rf out/product/halley2/system/usr/share/alsa/ucm/SDP4430
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/FMAnalog
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/voice
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/record
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/PandaBoard.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/voiceCall
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/hifiLP
rm -f out/product/halley2/system/usr/share/alsa/ucm/PandaBoard/hifi
rm -rf out/product/halley2/system/usr/share/alsa/ucm/PandaBoard
rm -f out/product/halley2/system/usr/share/alsa/ucm/tegraalc5632/tegraalc5632.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/tegraalc5632
rm -f out/product/halley2/system/usr/share/alsa/ucm/skylake-rt286/HiFi
rm -f out/product/halley2/system/usr/share/alsa/ucm/skylake-rt286/skylake-rt286.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/skylake-rt286/Hdmi2
rm -f out/product/halley2/system/usr/share/alsa/ucm/skylake-rt286/Hdmi1
rm -rf out/product/halley2/system/usr/share/alsa/ucm/skylake-rt286
rm -f out/product/halley2/system/usr/share/alsa/ucm/GoogleNyan/HiFi.conf
rm -f out/product/halley2/system/usr/share/alsa/ucm/GoogleNyan/GoogleNyan.conf
rm -rf out/product/halley2/system/usr/share/alsa/ucm/GoogleNyan
rm -f out/product/halley2/system/usr/share/glib-2.0/gdb/gobject_gdb.py
rm -f out/product/halley2/system/usr/share/glib-2.0/gdb/glib_gdb.py
rm -rf out/product/halley2/system/usr/share/glib-2.0/gdb
rm -rf out/product/halley2/system/run/sudo
