#!/bin/bash
rm -rf out/product/phoenix/systemOTA/.git
rm -rf out/product/phoenix/systemOTA/var/lib/sudo
rm -rf out/product/phoenix/systemOTA/var/lib/alsa
rm -f out/product/phoenix/systemOTA/var/lib/dbus
rm -rf out/product/phoenix/systemOTA/var/lib/sudo/lectured
rm -rf out/product/phoenix/systemOTA/run/sudo
rm -rf out/product/phoenix/systemOTA/run/dbus
rm -f out/product/phoenix/systemOTA/lib/libblkid.so.1.1.0
rm -f out/product/phoenix/systemOTA/lib/libanl.so.1
rm -f out/product/phoenix/systemOTA/lib/libblkid.so.1
rm -rf out/product/phoenix/systemOTA/lib/pkgconfig
rm -f out/product/phoenix/systemOTA/lib/libmount.so.1.1.0
rm -f out/product/phoenix/systemOTA/lib/libatomic.so.1
rm -f out/product/phoenix/systemOTA/lib/libuuid.so.1.3.0
rm -f out/product/phoenix/systemOTA/lib/libthread_db-1.0.so
rm -f out/product/phoenix/systemOTA/lib/libuuid.so.1
rm -f out/product/phoenix/systemOTA/lib/libanl-2.22.so
rm -rf out/product/phoenix/systemOTA/lib/bash
rm -f out/product/phoenix/systemOTA/lib/libthread_db.so.1
rm -f out/product/phoenix/systemOTA/lib/libatomic.so.1.1.0
rm -f out/product/phoenix/systemOTA/lib/libmount.so.1
rm -f out/product/phoenix/systemOTA/lib/pkgconfig/bash.pc
rm -f out/product/phoenix/systemOTA/lib/bash/sleep
rm -f out/product/phoenix/systemOTA/lib/bash/print
rm -f out/product/phoenix/systemOTA/lib/bash/push
rm -f out/product/phoenix/systemOTA/lib/bash/Makefile.inc
rm -f out/product/phoenix/systemOTA/lib/bash/truefalse
rm -f out/product/phoenix/systemOTA/lib/bash/mkdir
rm -f out/product/phoenix/systemOTA/lib/bash/logname
rm -f out/product/phoenix/systemOTA/lib/bash/id
rm -f out/product/phoenix/systemOTA/lib/bash/dirname
rm -f out/product/phoenix/systemOTA/lib/bash/uname
rm -f out/product/phoenix/systemOTA/lib/bash/unlink
rm -f out/product/phoenix/systemOTA/lib/bash/tee
rm -f out/product/phoenix/systemOTA/lib/bash/strftime
rm -f out/product/phoenix/systemOTA/lib/bash/tty
rm -f out/product/phoenix/systemOTA/lib/bash/finfo
rm -f out/product/phoenix/systemOTA/lib/bash/basename
rm -f out/product/phoenix/systemOTA/lib/bash/whoami
rm -f out/product/phoenix/systemOTA/lib/bash/pathchk
rm -f out/product/phoenix/systemOTA/lib/bash/mypid
rm -f out/product/phoenix/systemOTA/lib/bash/setpgid
rm -f out/product/phoenix/systemOTA/lib/bash/ln
rm -f out/product/phoenix/systemOTA/lib/bash/printenv
rm -f out/product/phoenix/systemOTA/lib/bash/rmdir
rm -f out/product/phoenix/systemOTA/lib/bash/head
rm -f out/product/phoenix/systemOTA/lib/bash/realpath
rm -f out/product/phoenix/systemOTA/lib/bash/sync
rm -f out/product/phoenix/systemOTA/bin/ipcalc
rm -f out/product/phoenix/systemOTA/bin/scriptreplay
rm -f out/product/phoenix/systemOTA/bin/conspy
rm -f out/product/phoenix/systemOTA/bin/rev
rm -f out/product/phoenix/systemOTA/bin/fsync
rm -f out/product/phoenix/systemOTA/bin/fatattr
rm -f out/product/phoenix/systemOTA/bin/kbd_mode
rm -f out/product/phoenix/systemOTA/bin/mpstat
rm -f out/product/phoenix/systemOTA/bin/base64
rm -f out/product/phoenix/systemOTA/bin/iostat
rm -f out/product/phoenix/systemOTA/bin/makemime
rm -f out/product/phoenix/systemOTA/bin/cttyhack
rm -f out/product/phoenix/systemOTA/bin/ionice
rm -f out/product/phoenix/systemOTA/bin/hush
rm -f out/product/phoenix/systemOTA/bin/ping6
rm -f out/product/phoenix/systemOTA/bin/bash
rm -f out/product/phoenix/systemOTA/bin/reformime
rm -f out/product/phoenix/systemOTA/bin/ed
rm -f out/product/phoenix/systemOTA/bin/stat
rm -f out/product/phoenix/systemOTA/etc/hostapd.conf
rm -f out/product/phoenix/systemOTA/etc/inputrc
rm -rf out/product/phoenix/systemOTA/etc/dbus-1
rm -rf out/product/phoenix/systemOTA/etc/libnl
rm -f out/product/phoenix/systemOTA/etc/sudoers
rm -f out/product/phoenix/systemOTA/etc/mke2fs.conf
rm -rf out/product/phoenix/systemOTA/etc/sudoers.d
rm -rf out/product/phoenix/systemOTA/etc/bluetooth
rm -rf out/product/phoenix/systemOTA/etc/ssl
rm -rf out/product/phoenix/systemOTA/etc/profile.d
rm -f out/product/phoenix/systemOTA/etc/network/if-pre-up.d/wait_iface
rm -f out/product/phoenix/systemOTA/etc/dbus-1/session.conf
rm -f out/product/phoenix/systemOTA/etc/dbus-1/system.conf
rm -rf out/product/phoenix/systemOTA/etc/dbus-1/system.d
rm -f out/product/phoenix/systemOTA/etc/dbus-1/system.d/wpa_supplicant.conf
rm -f out/product/phoenix/systemOTA/etc/dbus-1/system.d/bluetooth.conf
rm -f out/product/phoenix/systemOTA/etc/libnl/pktloc
rm -f out/product/phoenix/systemOTA/etc/libnl/classid
rm -f out/product/phoenix/systemOTA/etc/bluetooth/main.conf
rm -f out/product/phoenix/systemOTA/etc/bluetooth/rfcomm.conf
rm -rf out/product/phoenix/systemOTA/etc/ssl/certs
rm -rf out/product/phoenix/systemOTA/etc/ssl/misc
rm -rf out/product/phoenix/systemOTA/etc/ssl/man
rm -f out/product/phoenix/systemOTA/etc/ssl/openssl.cnf
rm -rf out/product/phoenix/systemOTA/etc/ssl/private
rm -rf out/product/phoenix/systemOTA/etc/ssl/man/man1
rm -rf out/product/phoenix/systemOTA/etc/ssl/man/man5
rm -rf out/product/phoenix/systemOTA/etc/ssl/man/man3
rm -rf out/product/phoenix/systemOTA/etc/ssl/man/man7
rm -f out/product/phoenix/systemOTA/etc/init.d/S30dbus
rm -f out/product/phoenix/systemOTA/etc/init.d/S50telnet
rm -f out/product/phoenix/systemOTA/etc/profile.d/umask.sh
rm -rf out/product/phoenix/systemOTA/usr/libexec
rm -f out/product/phoenix/systemOTA/usr/lib/libip4tc.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libtinyalsa.so.1
rm -f out/product/phoenix/systemOTA/usr/lib/libdbus-1.so.3
rm -f out/product/phoenix/systemOTA/usr/lib/libpcrecpp.so.0.0.1
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-xfrm-3.so.200.22.0
rm -f out/product/phoenix/systemOTA/usr/lib/libip6tc.so
rm -f out/product/phoenix/systemOTA/usr/lib/libcurses.so
rm -f out/product/phoenix/systemOTA/usr/lib/libuuid.so
rm -f out/product/phoenix/systemOTA/usr/lib/libip6tc.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libpcrecpp.so
rm -f out/product/phoenix/systemOTA/usr/lib/libe2p.so
rm -f out/product/phoenix/systemOTA/usr/lib/libglib-2.0.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libffi.so.6.0.4
rm -f out/product/phoenix/systemOTA/usr/lib/libgmodule-2.0.so
rm -f out/product/phoenix/systemOTA/usr/lib/libcom_err.so
rm -f out/product/phoenix/systemOTA/usr/lib/libexpat.so.1
rm -f out/product/phoenix/systemOTA/usr/lib/libasound.so.2.0.0
rm -f out/product/phoenix/systemOTA/usr/lib/libpcrecpp.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libglib-2.0.so.0.5000.2
rm -f out/product/phoenix/systemOTA/usr/lib/libiptc.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-nf-3.so.200.22.0
rm -f out/product/phoenix/systemOTA/usr/lib/libpcreposix.so.0.0.4
rm -f out/product/phoenix/systemOTA/usr/lib/libexpat.so
rm -f out/product/phoenix/systemOTA/usr/lib/libmount.so
rm -f out/product/phoenix/systemOTA/usr/lib/libip4tc.so.0.1.0
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-route-3.so.200
rm -f out/product/phoenix/systemOTA/usr/lib/libhistory.so.7
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-idiag-3.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgthread-2.0.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libturbojpeg.so
rm -f out/product/phoenix/systemOTA/usr/lib/libreadline.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgmodule-2.0.so.0.5000.2
rm -f out/product/phoenix/systemOTA/usr/lib/libturbojpeg.so.0.1.0
rm -f out/product/phoenix/systemOTA/usr/lib/libform.so.5.9
rm -f out/product/phoenix/systemOTA/usr/lib/libgmodule-2.0.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libstdc++.so.6.0.21
rm -f out/product/phoenix/systemOTA/usr/lib/libexpat.so.1.6.2
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-idiag-3.so.200
rm -f out/product/phoenix/systemOTA/usr/lib/libpcreposix.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libcheck.so.0.0.0
rm -f out/product/phoenix/systemOTA/usr/lib/libpcre.so.1
rm -f out/product/phoenix/systemOTA/usr/lib/libreadline.so.7
rm -f out/product/phoenix/systemOTA/usr/lib/libncurses.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgobject-2.0.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libtinyalsa.so
rm -f out/product/phoenix/systemOTA/usr/lib/libasound.so.2
rm -f out/product/phoenix/systemOTA/usr/lib/libmenu.so.5
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-xfrm-3.so
rm -rf out/product/phoenix/systemOTA/usr/lib/xtables
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-nf-3.so
rm -f out/product/phoenix/systemOTA/usr/lib/libffi.so.6
rm -f out/product/phoenix/systemOTA/usr/lib/libgthread-2.0.so.0.5000.2
rm -f out/product/phoenix/systemOTA/usr/lib/libpcre.so.1.2.8
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-route-3.so
rm -f out/product/phoenix/systemOTA/usr/lib/libglib-2.0.so
rm -f out/product/phoenix/systemOTA/usr/lib/libss.so.2.0
rm -f out/product/phoenix/systemOTA/usr/lib/libatomic.so.1
rm -f out/product/phoenix/systemOTA/usr/lib/libntfs-3g.so
rm -f out/product/phoenix/systemOTA/usr/lib/libopenobex.so
rm -f out/product/phoenix/systemOTA/usr/lib/libbluetooth.so.3
rm -f out/product/phoenix/systemOTA/usr/lib/libmenu.so.5.9
rm -f out/product/phoenix/systemOTA/usr/lib/libgthread-2.0.so
rm -f out/product/phoenix/systemOTA/usr/lib/libss.so.2
rm -f out/product/phoenix/systemOTA/usr/lib/libblkid.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgobject-2.0.so.0.5000.2
rm -f out/product/phoenix/systemOTA/usr/lib/libjpeg.so.8.1.2
rm -f out/product/phoenix/systemOTA/usr/lib/libhistory.so.7.0
rm -f out/product/phoenix/systemOTA/usr/lib/libntfs-3g.so.87
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-route-3.so.200.22.0
rm -f out/product/phoenix/systemOTA/usr/lib/libncurses.so.5.9
rm -f out/product/phoenix/systemOTA/usr/lib/libe2p.so.2.3
rm -f out/product/phoenix/systemOTA/usr/lib/libform.so
rm -f out/product/phoenix/systemOTA/usr/lib/libncurses.so.5
rm -f out/product/phoenix/systemOTA/usr/lib/libstdc++.so.6
rm -f out/product/phoenix/systemOTA/usr/lib/libcom_err.so.2.1
rm -f out/product/phoenix/systemOTA/usr/lib/libntfs-3g.so.87.0.0
rm -f out/product/phoenix/systemOTA/usr/lib/libpanel.so
rm -f out/product/phoenix/systemOTA/usr/lib/libmenu.so
rm -f out/product/phoenix/systemOTA/usr/lib/libip4tc.so
rm -f out/product/phoenix/systemOTA/usr/lib/libform.so.5
rm -f out/product/phoenix/systemOTA/usr/lib/libiptc.so.0.0.0
rm -f out/product/phoenix/systemOTA/usr/lib/libdbus-1.so
rm -f out/product/phoenix/systemOTA/usr/lib/libhistory.so
rm -f out/product/phoenix/systemOTA/usr/lib/libext2fs.so.2.4
rm -f out/product/phoenix/systemOTA/usr/lib/libdbus-1.so.3.14.10
rm -f out/product/phoenix/systemOTA/usr/lib/libjpeg.so
rm -rf out/product/phoenix/systemOTA/usr/lib/gio
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-nf-3.so.200
rm -f out/product/phoenix/systemOTA/usr/lib/libffi.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgio-2.0.so
rm -f out/product/phoenix/systemOTA/usr/lib/libturbojpeg.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libcom_err.so.2
rm -f out/product/phoenix/systemOTA/usr/lib/libxtables.so.12.0.0
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-idiag-3.so.200.22.0
rm -f out/product/phoenix/systemOTA/usr/lib/libip6tc.so.0.1.0
rm -f out/product/phoenix/systemOTA/usr/lib/libxtables.so.12
rm -f out/product/phoenix/systemOTA/usr/lib/libreadline.so.7.0
rm -f out/product/phoenix/systemOTA/usr/lib/libopenobex.so.1.4.1
rm -f out/product/phoenix/systemOTA/usr/lib/libext2fs.so.2
rm -f out/product/phoenix/systemOTA/usr/lib/libjpeg.so.8
rm -f out/product/phoenix/systemOTA/usr/lib/libgio-2.0.so.0.5000.2
rm -f out/product/phoenix/systemOTA/usr/lib/libpanel.so.5.9
rm -f out/product/phoenix/systemOTA/usr/lib/libbluetooth.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgio-2.0.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libasound.so
rm -f out/product/phoenix/systemOTA/usr/lib/libpanel.so.5
rm -f out/product/phoenix/systemOTA/usr/lib/libiptc.so
rm -f out/product/phoenix/systemOTA/usr/lib/libatomic.so.1.1.0
rm -f out/product/phoenix/systemOTA/usr/lib/libnl-xfrm-3.so.200
rm -f out/product/phoenix/systemOTA/usr/lib/libcheck.so.0
rm -f out/product/phoenix/systemOTA/usr/lib/libe2p.so.2
rm -f out/product/phoenix/systemOTA/usr/lib/libpcreposix.so
rm -f out/product/phoenix/systemOTA/usr/lib/libext2fs.so
rm -f out/product/phoenix/systemOTA/usr/lib/libgobject-2.0.so
rm -f out/product/phoenix/systemOTA/usr/lib/libbluetooth.so.3.13.0
rm -f out/product/phoenix/systemOTA/usr/lib/libopenobex.so.1
rm -rf out/product/phoenix/systemOTA/usr/lib/terminfo
rm -f out/product/phoenix/systemOTA/usr/lib/libss.so
rm -f out/product/phoenix/systemOTA/usr/lib/libxtables.so
rm -f out/product/phoenix/systemOTA/usr/lib/libtinyalsa.so.1.1.0
rm -f out/product/phoenix/systemOTA/usr/lib/libcheck.so
rm -f out/product/phoenix/systemOTA/usr/lib/libpcre.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_conntrack.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_TOS.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_MASQUERADE.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_limit.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_sctp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_tcpmss.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_dscp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_CONNSECMARK.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_TTL.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_hbh.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_LOG.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_icmp6.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_SNAT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_SNPT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_icmp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_IDLETIMER.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_TCPOPTSTRIP.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_CLASSIFY.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_RATEEST.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_physdev.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_hl.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_mark.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_NFLOG.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_SET.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_comment.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_ah.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_bpf.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_connbytes.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_mh.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_rpfilter.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_REJECT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_recent.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_policy.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_REDIRECT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_udp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_NFQUEUE.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_NOTRACK.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libebt_mark_m.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_u32.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_ipv6header.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_ttl.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_state.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_MARK.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_time.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_TEE.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_LED.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_SNAT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_ah.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_socket.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_connmark.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_DNAT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_tos.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_iprange.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_MASQUERADE.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libebt_ip.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_statistic.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_CT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_cpu.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libebt_log.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_DNPT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_ecn.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_CLUSTERIP.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_TCPMSS.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_addrtype.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_cgroup.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_standard.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_helper.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_pkttype.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_multiport.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_dst.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_devgroup.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_hashlimit.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_HMARK.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_ULOG.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_tcp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_ipvs.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_quota.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_rt.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_CONNMARK.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_mac.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_TPROXY.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_eui64.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_mangle.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_NETMAP.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_DNAT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_realm.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_ipcomp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_TRACE.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libebt_802_3.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_SYNPROXY.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_set.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_connlimit.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_nfacct.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_REJECT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_rateest.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_DSCP.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_dccp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_REDIRECT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_LOG.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_AUDIT.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_cluster.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_length.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_SECMARK.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_CHECKSUM.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_NETMAP.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_HL.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_owner.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_osf.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_esp.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libxt_string.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libipt_ECN.so
rm -f out/product/phoenix/systemOTA/usr/lib/xtables/libip6t_frag.so
rm -rf out/product/phoenix/systemOTA/usr/lib/gio/modules
rm -f out/product/phoenix/systemOTA/usr/bin/pkill
rm -f out/product/phoenix/systemOTA/usr/bin/rx
rm -f out/product/phoenix/systemOTA/usr/bin/pwdx
rm -f out/product/phoenix/systemOTA/usr/bin/irxfer
rm -f out/product/phoenix/systemOTA/usr/bin/tree
rm -f out/product/phoenix/systemOTA/usr/bin/ntfs-3g.usermap
rm -f out/product/phoenix/systemOTA/usr/bin/obex_tcp
rm -f out/product/phoenix/systemOTA/usr/bin/aserver
rm -f out/product/phoenix/systemOTA/usr/bin/chpst
rm -f out/product/phoenix/systemOTA/usr/bin/ircp
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-launch
rm -f out/product/phoenix/systemOTA/usr/bin/wall
rm -f out/product/phoenix/systemOTA/usr/bin/sudoedit
rm -f out/product/phoenix/systemOTA/usr/bin/gatttool
rm -f out/product/phoenix/systemOTA/usr/bin/sudo
rm -f out/product/phoenix/systemOTA/usr/bin/ntfs-3g.secaudit
rm -f out/product/phoenix/systemOTA/usr/bin/ntfs-3g.probe
rm -f out/product/phoenix/systemOTA/usr/bin/irobex_palm3
rm -f out/product/phoenix/systemOTA/usr/bin/ttysize
rm -f out/product/phoenix/systemOTA/usr/bin/runsv
rm -f out/product/phoenix/systemOTA/usr/bin/ftpget
rm -f out/product/phoenix/systemOTA/usr/bin/fgconsole
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-update-activation-environment
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-uuidgen
rm -f out/product/phoenix/systemOTA/usr/bin/nsenter
rm -f out/product/phoenix/systemOTA/usr/bin/pscan
rm -f out/product/phoenix/systemOTA/usr/bin/svc
rm -f out/product/phoenix/systemOTA/usr/bin/smemcap
rm -f out/product/phoenix/systemOTA/usr/bin/nc
rm -f out/product/phoenix/systemOTA/usr/bin/tcpsvd
rm -f out/product/phoenix/systemOTA/usr/bin/cryptpw
rm -f out/product/phoenix/systemOTA/usr/bin/envdir
rm -f out/product/phoenix/systemOTA/usr/bin/sudoreplay
rm -f out/product/phoenix/systemOTA/usr/bin/iptables-xml
rm -f out/product/phoenix/systemOTA/usr/bin/aplay
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-send
rm -f out/product/phoenix/systemOTA/usr/bin/pmap
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-monitor
rm -f out/product/phoenix/systemOTA/usr/bin/sdptool
rm -f out/product/phoenix/systemOTA/usr/bin/l2ping
rm -f out/product/phoenix/systemOTA/usr/bin/hcitool
rm -f out/product/phoenix/systemOTA/usr/bin/softlimit
rm -f out/product/phoenix/systemOTA/usr/bin/blkdiscard
rm -f out/product/phoenix/systemOTA/usr/bin/unlink
rm -f out/product/phoenix/systemOTA/usr/bin/split
rm -f out/product/phoenix/systemOTA/usr/bin/tinyplay
rm -f out/product/phoenix/systemOTA/usr/bin/gio-querymodules
rm -f out/product/phoenix/systemOTA/usr/bin/users
rm -f out/product/phoenix/systemOTA/usr/bin/lpq
rm -f out/product/phoenix/systemOTA/usr/bin/script
rm -f out/product/phoenix/systemOTA/usr/bin/amixer
rm -f out/product/phoenix/systemOTA/usr/bin/rfcomm
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-run-session
rm -f out/product/phoenix/systemOTA/usr/bin/cal
rm -f out/product/phoenix/systemOTA/usr/bin/showkey
rm -f out/product/phoenix/systemOTA/usr/bin/lpr
rm -f out/product/phoenix/systemOTA/usr/bin/ciptool
rm -f out/product/phoenix/systemOTA/usr/bin/groups
rm -f out/product/phoenix/systemOTA/usr/bin/ntfs-3g
rm -f out/product/phoenix/systemOTA/usr/bin/strace
rm -f out/product/phoenix/systemOTA/usr/bin/gdbserver
rm -f out/product/phoenix/systemOTA/usr/bin/runsvdir
rm -f out/product/phoenix/systemOTA/usr/bin/tinymix
rm -f out/product/phoenix/systemOTA/usr/bin/flock
rm -f out/product/phoenix/systemOTA/usr/bin/hd
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-daemon
rm -f out/product/phoenix/systemOTA/usr/bin/sum
rm -f out/product/phoenix/systemOTA/usr/bin/pcregrep
rm -f out/product/phoenix/systemOTA/usr/bin/envuidgid
rm -f out/product/phoenix/systemOTA/usr/bin/whois
rm -f out/product/phoenix/systemOTA/usr/bin/man
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-test-tool
rm -f out/product/phoenix/systemOTA/usr/bin/nmeter
rm -f out/product/phoenix/systemOTA/usr/bin/obex_test
rm -f out/product/phoenix/systemOTA/usr/bin/gio
rm -f out/product/phoenix/systemOTA/usr/bin/traceroute6
rm -f out/product/phoenix/systemOTA/usr/bin/dbus-cleanup-sockets
rm -f out/product/phoenix/systemOTA/usr/bin/ftpput
rm -f out/product/phoenix/systemOTA/usr/bin/hostapd_cli
rm -f out/product/phoenix/systemOTA/usr/bin/tinycap
rm -f out/product/phoenix/systemOTA/usr/bin/volname
rm -f out/product/phoenix/systemOTA/usr/bin/sv
rm -f out/product/phoenix/systemOTA/usr/bin/gdbus
rm -f out/product/phoenix/systemOTA/usr/bin/pcretest
rm -f out/product/phoenix/systemOTA/usr/bin/lowntfs-3g
rm -f out/product/phoenix/systemOTA/usr/bin/strace-log-merge
rm -f out/product/phoenix/systemOTA/usr/bin/gsettings
rm -f out/product/phoenix/systemOTA/usr/bin/setuidgid
rm -f out/product/phoenix/systemOTA/usr/bin/tinypcminfo
rm -f out/product/phoenix/systemOTA/usr/bin/arecord
rm -f out/product/phoenix/systemOTA/usr/bin/bzip2
rm -f out/product/phoenix/systemOTA/usr/bin/beep
rm -f out/product/phoenix/systemOTA/usr/bin/gapplication
rm -f out/product/phoenix/systemOTA/usr/bin/pgrep
rm -f out/product/phoenix/systemOTA/usr/bin/timeout
rm -f out/product/phoenix/systemOTA/usr/bin/udpsvd
rm -f out/product/phoenix/systemOTA/usr/bin/unshare
rm -f out/product/phoenix/systemOTA/usr/bin/mkpasswd
rm -f out/product/phoenix/systemOTA/usr/bin/gresource
rm -f out/product/phoenix/systemOTA/usr/bin/pstree
rm -f out/product/phoenix/systemOTA/usr/bin/truncate
rm -rf out/product/phoenix/systemOTA/usr/share/glib-2.0
rm -rf out/product/phoenix/systemOTA/usr/share/bash-completion
rm -rf out/product/phoenix/systemOTA/usr/share/alsa
rm -rf out/product/phoenix/systemOTA/usr/share/dbus-1
rm -rf out/product/phoenix/systemOTA/usr/share/gettext
rm -rf out/product/phoenix/systemOTA/usr/share/locale
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo
rm -rf out/product/phoenix/systemOTA/usr/share/glib-2.0/schemas
rm -rf out/product/phoenix/systemOTA/usr/share/glib-2.0/gdb
rm -f out/product/phoenix/systemOTA/usr/share/glib-2.0/gdb/glib_gdb.py
rm -f out/product/phoenix/systemOTA/usr/share/glib-2.0/gdb/gobject_gdb.py
rm -rf out/product/phoenix/systemOTA/usr/share/bash-completion/completions
rm -f out/product/phoenix/systemOTA/usr/share/bash-completion/completions/uuidgen
rm -f out/product/phoenix/systemOTA/usr/share/bash-completion/completions/gdbus
rm -f out/product/phoenix/systemOTA/usr/share/bash-completion/completions/gsettings
rm -f out/product/phoenix/systemOTA/usr/share/bash-completion/completions/gapplication
rm -f out/product/phoenix/systemOTA/usr/share/bash-completion/completions/gresource
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/topology
rm -f out/product/phoenix/systemOTA/usr/share/alsa/alsa.conf
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/alsa.conf.d
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/pcm
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/cards
rm -f out/product/phoenix/systemOTA/usr/share/alsa/sndo-mixer.alisp
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/topology/broadwell
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/topology/sklrt286
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/topology/bxtrt298
rm -f out/product/phoenix/systemOTA/usr/share/alsa/topology/broadwell/broadwell.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/topology/sklrt286/skl_i2s.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/topology/bxtrt298/bxt_i2s.conf
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/PAZ00
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/tegraalc5632
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/VEYRON-I2S
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/GoogleNyan
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/DB410c
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/DAISY-I2S
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/chtrt5645
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/skylake-rt286
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/ucm/broadwell-rt286
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/voice
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/FMAnalog
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/record
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/hifiLP
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/PandaBoardES.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/hifi
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoardES/voiceCall
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/SDP4430.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/voice
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/FMAnalog
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/record
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/hifiLP
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/hifi
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/SDP4430/voiceCall
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PAZ00/HiFi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PAZ00/PAZ00.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PAZ00/Record.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/voice
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/PandaBoard.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/FMAnalog
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/record
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/hifiLP
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/hifi
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/PandaBoard/voiceCall
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/tegraalc5632/tegraalc5632.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/VEYRON-I2S/HiFi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/VEYRON-I2S/VEYRON-I2S.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/GoogleNyan/HiFi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/GoogleNyan/GoogleNyan.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/DB410c/DB410c.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/DB410c/HiFi
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/DB410c/HDMI
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/DAISY-I2S/HiFi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/DAISY-I2S/DAISY-I2S.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/chtrt5645/HiFi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/chtrt5645/chtrt5645.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/skylake-rt286/Hdmi2
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/skylake-rt286/skylake-rt286.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/skylake-rt286/HiFi
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/skylake-rt286/Hdmi1
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/broadwell-rt286/broadwell-rt286.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/ucm/broadwell-rt286/HiFi
rm -f out/product/phoenix/systemOTA/usr/share/alsa/alsa.conf.d/README
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/surround40.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/modem.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/dsnoop.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/rear.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/surround51.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/default.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/iec958.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/hdmi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/surround50.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/front.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/surround71.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/dmix.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/center_lfe.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/surround21.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/dpl.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/surround41.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/pcm/side.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ATIIXP-MODEM.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Loopback.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Audigy2.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/aliases.alisp
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ENS1370.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/PMacToonie.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/EMU10K1.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/PS3.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VIA686A.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/aliases.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CMI8738-MC6.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VIA8233A.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VXPocket.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/AU8810.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/AU8820.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/YMF744.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VX222.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/GUS.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CMI8338.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CMI8738-MC8.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Audigy.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Aureon51.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VIA8233.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CS46xx.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/RME9636.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/RME9652.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ENS1371.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/PMac.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Maestro3.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Echo_Echo3G.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/Aureon71.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ICH.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/FireWave.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/SB-XFi.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/FWSpeakers.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CMI8788.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/AACI.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VIA8237.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/AU8830.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ICH-MODEM.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ATIIXP-SPDMA.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/HDA-Intel.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/TRID4DWAVENX.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/PC-Speaker.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CA0106.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/SI7018.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ES1968.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/EMU10K1X.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ICE1724.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/CMI8338-SWIEC.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/FM801.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ICH4.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ICE1712.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/VXPocket440.conf
rm -rf out/product/phoenix/systemOTA/usr/share/alsa/cards/SI7018
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/USB-Audio.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/ATIIXP.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/NFORCE.conf
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/SI7018/sndoc-mixer.alisp
rm -f out/product/phoenix/systemOTA/usr/share/alsa/cards/SI7018/sndop-mixer.alisp
rm -f out/product/phoenix/systemOTA/usr/share/dbus-1/session.conf
rm -rf out/product/phoenix/systemOTA/usr/share/dbus-1/services
rm -rf out/product/phoenix/systemOTA/usr/share/dbus-1/system-services
rm -f out/product/phoenix/systemOTA/usr/share/dbus-1/system.conf
rm -rf out/product/phoenix/systemOTA/usr/share/dbus-1/system.d
rm -rf out/product/phoenix/systemOTA/usr/share/dbus-1/session.d
rm -f out/product/phoenix/systemOTA/usr/share/dbus-1/system-services/org.bluez.service
rm -rf out/product/phoenix/systemOTA/usr/share/gettext/its
rm -f out/product/phoenix/systemOTA/usr/share/gettext/its/gschema.its
rm -f out/product/phoenix/systemOTA/usr/share/gettext/its/gschema.loc
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo/p
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo/s
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo/x
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo/a
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo/v
rm -rf out/product/phoenix/systemOTA/usr/share/terminfo/l
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/p/putty
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/p/putty-vt100
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/s/screen
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/x/xterm-xfree86
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/x/xterm
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/x/xterm-color
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/a/ansi
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/v/vt220
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/v/vt100
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/v/vt102
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/v/vt100-putty
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/v/vt200
rm -f out/product/phoenix/systemOTA/usr/share/terminfo/l/linux
rm -f out/product/phoenix/systemOTA/usr/sbin/iptables-restore
rm -f out/product/phoenix/systemOTA/usr/sbin/ubiattach
rm -f out/product/phoenix/systemOTA/usr/sbin/fakeidentd
rm -f out/product/phoenix/systemOTA/usr/sbin/i2cget
rm -f out/product/phoenix/systemOTA/usr/sbin/xtables-multi
rm -f out/product/phoenix/systemOTA/usr/sbin/ip6tables-save
rm -f out/product/phoenix/systemOTA/usr/sbin/mkfs.ext2
rm -f out/product/phoenix/systemOTA/usr/sbin/i2cdetect
rm -f out/product/phoenix/systemOTA/usr/sbin/i2cdump
rm -f out/product/phoenix/systemOTA/usr/sbin/mkfs.ext3
rm -f out/product/phoenix/systemOTA/usr/sbin/tftpd
rm -f out/product/phoenix/systemOTA/usr/sbin/rtcwake
rm -f out/product/phoenix/systemOTA/usr/sbin/ntpd
rm -f out/product/phoenix/systemOTA/usr/sbin/ftpd
rm -f out/product/phoenix/systemOTA/usr/sbin/iptables-save
rm -f out/product/phoenix/systemOTA/usr/sbin/ubiblock
rm -f out/product/phoenix/systemOTA/usr/sbin/sendmail
rm -f out/product/phoenix/systemOTA/usr/sbin/ifplugd
rm -f out/product/phoenix/systemOTA/usr/sbin/lpd
rm -f out/product/phoenix/systemOTA/usr/sbin/nandtest
rm -f out/product/phoenix/systemOTA/usr/sbin/nbd-client
rm -f out/product/phoenix/systemOTA/usr/sbin/i2cset
rm -f out/product/phoenix/systemOTA/usr/sbin/ubimkvol
rm -f out/product/phoenix/systemOTA/usr/sbin/ubiformat
rm -f out/product/phoenix/systemOTA/usr/sbin/telnetd
rm -f out/product/phoenix/systemOTA/usr/sbin/chpasswd
rm -f out/product/phoenix/systemOTA/usr/sbin/brctl
rm -f out/product/phoenix/systemOTA/usr/sbin/mkfs.ext4
rm -f out/product/phoenix/systemOTA/usr/sbin/ubinize
rm -f out/product/phoenix/systemOTA/usr/sbin/fbset
rm -f out/product/phoenix/systemOTA/usr/sbin/ubirsvol
rm -f out/product/phoenix/systemOTA/usr/sbin/add-shell
rm -f out/product/phoenix/systemOTA/usr/sbin/mke2fs
rm -f out/product/phoenix/systemOTA/usr/sbin/iptables
rm -f out/product/phoenix/systemOTA/usr/sbin/hciconfig
rm -f out/product/phoenix/systemOTA/usr/sbin/mkfs.ext4dev
rm -f out/product/phoenix/systemOTA/usr/sbin/chat
rm -f out/product/phoenix/systemOTA/usr/sbin/bluetoothd
rm -f out/product/phoenix/systemOTA/usr/sbin/ubirmvol
rm -f out/product/phoenix/systemOTA/usr/sbin/visudo
rm -f out/product/phoenix/systemOTA/usr/sbin/svlogd
rm -f out/product/phoenix/systemOTA/usr/sbin/ubidetach
rm -f out/product/phoenix/systemOTA/usr/sbin/e4crypt
rm -f out/product/phoenix/systemOTA/usr/sbin/powertop
rm -f out/product/phoenix/systemOTA/usr/sbin/ubinfo
rm -f out/product/phoenix/systemOTA/usr/sbin/hciattach
rm -f out/product/phoenix/systemOTA/usr/sbin/hostapd
rm -f out/product/phoenix/systemOTA/usr/sbin/rdev
rm -f out/product/phoenix/systemOTA/usr/sbin/readahead
rm -f out/product/phoenix/systemOTA/usr/sbin/ip6tables-restore
rm -f out/product/phoenix/systemOTA/usr/sbin/remove-shell
rm -f out/product/phoenix/systemOTA/usr/sbin/popmaildir
rm -f out/product/phoenix/systemOTA/usr/sbin/ip6tables
rm -f out/product/phoenix/systemOTA/usr/sbin/ubiupdatevol
rm -f out/product/phoenix/systemOTA/usr/sbin/httpd
rm -f out/product/phoenix/systemOTA/usr/sbin/ubirename
rm -f out/product/phoenix/systemOTA/usr/sbin/ubicrc32
rm -f out/product/phoenix/systemOTA/usr/sbin/setfont
rm -rf out/product/phoenix/systemOTA/usr/libexec/sudo
rm -f out/product/phoenix/systemOTA/usr/libexec/dbus-daemon-launch-helper
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/sudoers.so
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/libsudo_util.so.0
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/sudo_noexec.so
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/libsudo_util.so.0.0.0
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/libsudo_util.so
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/system_group.so
rm -f out/product/phoenix/systemOTA/usr/libexec/sudo/group_file.so
rm -f out/product/phoenix/systemOTA/.git/index
rm -f out/product/phoenix/systemOTA/.git/hooks
rm -f out/product/phoenix/systemOTA/.git/svn
rm -f out/product/phoenix/systemOTA/.git/logs
rm -f out/product/phoenix/systemOTA/.git/config
rm -f out/product/phoenix/systemOTA/.git/packed-refs
rm -f out/product/phoenix/systemOTA/.git/description
rm -f out/product/phoenix/systemOTA/.git/refs
rm -f out/product/phoenix/systemOTA/.git/rr-cache
rm -f out/product/phoenix/systemOTA/.git/HEAD
rm -f out/product/phoenix/systemOTA/.git/info
rm -f out/product/phoenix/systemOTA/.git/objects
rm -f out/product/phoenix/systemOTA/sbin/depmod
rm -f out/product/phoenix/systemOTA/sbin/logread
rm -f out/product/phoenix/systemOTA/sbin/fbsplash
rm -f out/product/phoenix/systemOTA/sbin/mkdosfs
rm -f out/product/phoenix/systemOTA/sbin/mkfs.ext2
rm -f out/product/phoenix/systemOTA/sbin/mkfs.minix
rm -f out/product/phoenix/systemOTA/sbin/findfs
rm -f out/product/phoenix/systemOTA/sbin/modinfo
rm -f out/product/phoenix/systemOTA/sbin/acpid
rm -f out/product/phoenix/systemOTA/sbin/iwgetid
rm -f out/product/phoenix/systemOTA/sbin/adjtimex
rm -f out/product/phoenix/systemOTA/sbin/uevent
rm -f out/product/phoenix/systemOTA/sbin/mkfs.msdos
rm -f out/product/phoenix/systemOTA/sbin/bootchartd
rm -f out/product/phoenix/systemOTA/sbin/mount.ntfs-3g
rm -f out/product/phoenix/systemOTA/sbin/ipneigh
rm -f out/product/phoenix/systemOTA/sbin/iwconfig
rm -f out/product/phoenix/systemOTA/sbin/blkid
rm -f out/product/phoenix/systemOTA/sbin/mke2fs
rm -f out/product/phoenix/systemOTA/sbin/mkfs.vfat
rm -f out/product/phoenix/systemOTA/sbin/mkfs.fat
rm -f out/product/phoenix/systemOTA/sbin/tunctl
rm -f out/product/phoenix/systemOTA/sbin/mount.lowntfs-3g
rm -f out/product/phoenix/systemOTA/sbin/fdisk
rm -f out/product/phoenix/systemOTA/sbin/slattach
rm -f out/product/phoenix/systemOTA/sbin/iwlist
rm -f out/product/phoenix/systemOTA/sbin/blockdev
rm -f out/product/phoenix/systemOTA/sbin/raidautorun
rm -f out/product/phoenix/systemOTA/sbin/fsck.minix
rm -f out/product/phoenix/systemOTA/sbin/iwpriv
rm -f out/product/phoenix/systemOTA/sbin/iwspy
rm -f out/product/phoenix/systemOTA/sbin/ifenslave
